version: 2
updates:
- package-ecosystem: npm
  directory: "/app/experimenter/static/rapid"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/app/experimenter/static/core"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/app/requirements"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
