version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: weekly
  target-branch: main
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-patch"]
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: weekly
  target-branch: main
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-patch"]
- package-ecosystem: pip
  directory: "/app/tests"
  schedule:
    interval: weekly
  target-branch: main
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-patch"]
