version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: weekly
  target-branch: main
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: weekly
  target-branch: main
- package-ecosystem: pip
  directory: "/app/tests"
  schedule:
    interval: weekly
  target-branch: main
