version: 2
updates:
- package-ecosystem: npm
  directory: "/app/experimenter/nimbus-ui"
  schedule:
    interval: weekly
  target-branch: dependencies
- package-ecosystem: npm
  directory: "/app/experimenter/legacy-ui/rapid"
  schedule:
    interval: weekly
  target-branch: dependencies
- package-ecosystem: npm
  directory: "/app/experimenter/legacy-ui/core"
  schedule:
    interval: weekly
  target-branch: dependencies
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: weekly
  target-branch: dependencies
- package-ecosystem: pip
  directory: "/app/tests"
  schedule:
    interval: weekly
  target-branch: dependencies
