version: "3"

services:
  firefox:
    image: b4handjr/selenium-firefox:python3-latest
    env_file: .env
    environment:
      - MOZ_HEADLESS
    volumes:
      - .:/code
      - /code/app/tests/integration/.tox
    links:
      - nginx
    expose:
      - "4444"
    ports:
      - "5900:5900"
    shm_size: 2g
