version: "3"

services:
  app:
    image: app:build
    env_file: .env
    stdin_open: true
    tty: true
    links:
      - db
      - redis
      - kinto
    ports:
      - "7001:7001"
    volumes:
      - ./app:/app
      - /app/node_modules/
      - /app/experimenter/legacy-ui/core/node_modules/
      - /app/experimenter/legacy-ui/rapid/node_modules/
      - /app/experimenter/legacy-ui/visualization/node_modules/
      - assets_volume:/app/experimenter/legacy-ui/assets/
      - /app/experimenter/nimbus-ui/node_modules/
      - /app/experimenter/nimbus-ui/build/
      - static_volume:/app/experimenter/served/
    command: bash -c "/app/bin/wait-for-it.sh kinto:8888 -- python bin/setup_kinto.py;/app/bin/wait-for-it.sh db:5432 -- python /app/manage.py collectstatic --noinput;python /app/manage.py runserver 0:7001"

  yarn-core:
    image: app:build
    env_file: .env
    tty: true
    volumes:
      - ./app:/app
      - /app/node_modules/
      - /app/experimenter/legacy-ui/core/node_modules/
      - assets_volume:/app/experimenter/legacy-ui/assets/
      - static_volume:/app/experimenter/served/
    command: bash -c "yarn workspace @experimenter/core watch"

  yarn-rapid:
    image: app:build
    env_file: .env
    tty: true
    volumes:
      - ./app:/app
      - /app/node_modules/
      - /app/experimenter/legacy-ui/rapid/node_modules/
      - assets_volume:/app/experimenter/legacy-ui/assets/
      - static_volume:/app/experimenter/served/
    command: bash -c "yarn workspace @experimenter/rapid watch"

  yarn-visualization:
    image: app:build
    env_file: .env
    tty: true
    volumes:
      - ./app:/app
      - /app/node_modules/
      - /app/experimenter/legacy-ui/visualization/node_modules/
      - assets_volume:/app/experimenter/legacy-ui/assets/
      - static_volume:/app/experimenter/served/
    command: bash -c "yarn workspace @experimenter/visualization watch"

  worker:
    image: app:build
    env_file: .env
    links:
      - db
      - redis
    volumes:
      - ./app:/app
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- celery -A experimenter worker -l debug"

  beat:
    image: app:build
    env_file: .env
    links:
      - db
      - redis
    volumes:
      - ./app:/app
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- celery -A experimenter beat --pidfile /celerybeat.pid -s /celerybeat-schedule -l debug"

  nginx:
    build: ./nginx
    env_file: .env
    links:
      - app
    ports:
      - "443:443"
    volumes:
      - static_volume:/app/experimenter/served/

  db:
    restart: always
    image: postgres:9.6.17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql

  redis:
    image: redis
    ports:
      - "6379:6379"

  kinto:
    image: mozilla/kinto-dist
    environment:
      KINTO_INI: /etc/kinto.ini
    ports:
      - "8888:8888"
    links:
      - autograph
    volumes:
      - ./kinto/server.ini:/etc/kinto.ini
      - kinto_volume:/attachments

  autograph:
    image: mozilla/autograph
    ports:
      - "8000:8000"

volumes:
  db_volume:
  static_volume:
  assets_volume:
  kinto_volume:
