version: "3"

services:
  app:
    image: app:build
    env_file: .env.sample
    environment:
      - DEBUG=False
    volumes:
      - /app/node_modules/
    links:
      - db

  db:
    restart: always
    image: postgres:9.6.17
    environment:
      POSTGRES_PASSWORD: postgres