version: "3"

services:
  app:
    links:
      - db
      - redis
      - normandy

  worker:
    links:
      - db
      - redis
      - normandy

  delivery-console:
    build:
      context: ./delivery-console
      dockerfile: $PWD/delivery-console/Dockerfile
    command: bash -c "REACT_APP_EXPERIMENTER_API_ROOT_URL=https://localhost/api/ REACT_APP_NORMANDY_ADMIN_API_ROOT_URL=https://localhost:8000/api/ yarn start"
    links:
      - normandy
    ports:
      - "3000:3000"
    networks:
      - private_nw
      - public_nw

  normandy:
    build:
      context: ./normandy
      dockerfile: $PWD/normandy/Dockerfile.development
    command: bash -c "/app/bin/wait-for-it.sh normandy_db:5431; ./bin/download_geolite2.sh; python manage.py migrate; python manage.py update_actions; python manage.py initial_data; ./bin/runsslserver.sh 0.0.0.0:8000"
    links:
      - normandy_db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@normandy_db/normandy
      - DJANGO_ALLOWED_HOSTS=normandy,localhost
    ports:
      - "8000:8000"
    networks:
      - private_nw
      - public_nw

  normandy_db:
    restart: always
    image: postgres:9.6.17
    ports:
      - "5431:5432"
    networks:
      - private_nw
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: normandy
