version: "3"

services:
  app:
    image: app:build
    env_file: .env.sample
    environment:
      - DEBUG=False
      - CIRCLE_PULL_REQUEST
      - CIRCLE_BRANCH
      - STORYBOOKS_GITHUB_REPO
      - STORYBOOKS_GITHUB_TOKEN
      - STORYBOOKS_GCP_PROJECT_ID
      - STORYBOOKS_GCP_BUCKET
      - STORYBOOKS_GCP_PRIVATE_KEY_BASE64
      - STORYBOOKS_GCP_CLIENT_EMAIL
    volumes:
      - /app/node_modules/
    links:
      - db

  db:
    restart: always
    image: postgres:9.6.17
    environment:
      POSTGRES_PASSWORD: postgres