version: "3"

services:
  app:
    image: app:build
    env_file: .env.sample
    volumes:
      - ./app:/app
    links:
      - db
    networks:
      - private_nw

  db:
    restart: always
    image: postgres:9.6
    networks:
      - private_nw

networks:
  private_nw:
    internal: true
