version: "3"

services:
  app:
    image: app:build
    env_file: .env
    stdin_open: true
    tty: true
    links:
      - db
    volumes:
      - ./app:/app
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- python /app/manage.py collectstatic --noinput; python /app/manage.py runserver 0:7001"
    networks:
      - private_nw
      - public_nw

  nginx:
    build: ./nginx
    env_file: .env
    links:
      - app
    ports:
      - "80:80"
    networks:
      - private_nw
      - public_nw

  db:
    restart: always
    image: postgres:9.6
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - private_nw

volumes:
  db_volume:

networks:
  private_nw:
    internal: true
  public_nw:
