version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
    resource_class: large
    working_directory: ~/experimenter
    steps:
      - run:
          name: Docker info
          command: docker -v
      - run:
          name: Docker compose info
          command: docker-compose -v
      - checkout
      - run:
          name: Build docker images
          command:
            make test_build

  check:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
    resource_class: large
    working_directory: ~/experimenter
    steps:
      - run:
          name: Docker info
          command: docker -v
      - run:
          name: Docker compose info
          command: docker-compose -v
      - checkout
      - run:
          name: Run tests and linting
          command: make check

  publish_storybooks:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
    resource_class: medium
    working_directory: ~/experimenter
    steps:
      - run:
          name: Docker info
          command: docker -v
      - run:
          name: Docker compose info
          command: docker-compose -v
      - checkout
      - run:
          name: Publish Storybooks
          command: |
            ./scripts/store_git_info.sh
            make publish_storybooks

  integration:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
    resource_class: xlarge
    working_directory: ~/experimenter
    steps:
      - run:
          name: Docker info
          command: docker -v
      - run:
          name: Docker compose info
          command: docker-compose -v
      - checkout
      - run:
          name: Run integration tests
          command: |
            cp .env.sample .env
            make refresh
            make up_prod_detached
            make integration_test

  deploy:
    working_directory: ~/experimenter
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
    steps:
      - checkout
      - deploy:
          name: Deploy to latest
          command: |
            ./scripts/store_git_info.sh
            make build_prod
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag app:deploy ${DOCKERHUB_REPO}:latest
            docker push ${DOCKERHUB_REPO}:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: build
      - check:
          name: check
          requires:
            - build
      - publish_storybooks:
          name: publish_storybooks
          requires:
            - build
      - integration:
          name: integration
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
      - deploy:
          filters:
            branches:
              only: main
          requires:
           - check
